DOMAIN = "nano_pk"

CONF_HOST = "host"
CONF_FORMAT = "msgformat"
CONF_NAME = "devicename"
CONF_PARAMS = "parameters"
CONF_PARAMS_STANDARD = "STANDARD"
CONF_PARAMS_FULL = "FULL"
CONF_LANG = "language"
CONF_LANG_EN = "EN"
CONF_LANG_DE = "DE"
CONF_UNIQUE_ID = "unique_id"

BRIDGE_STATE_OK = "OK"
BRIDGE_STATE_DISCONNECTED = "Disconnected"
BRIDGE_TIMEOUT = 10.0
